### ISSUE TITLE
Error on `bundle install`

### ISSUE THREAD

**Issue by stem** [seand7565/solidus_user_guides#2]
Hi @seand7565, thank you for this extension !

Unfortunately, the README seems wrong in the installation instructions.
As instructed, I've added in my Gemfile
```
gem 'solidus_user_guides'
```

but when I bundle install, I get : 
```
~/Projects/epicery/api (feature/solidus-user-guide *) $ bundle install
Fetching gem metadata from https://rubygems.org/........
Fetching gem metadata from https://rubygems.org/.
Could not find gem 'solidus_user_guides' in any of the gem sources listed in your Gemfile.
```

I guess this is because you never created a release because it works when getting it directly from GitHub.
I don't know what your preference is, so please, let me know if you wanna do a release or if I should make a pull request with this small change in the README :

    Installation
    ------------
    
    Add solidus_user_guides to your Gemfile:
    
    ```ruby
    gem 'solidus_user_guides', github: 'seand7565/solidus_user_guides'
    ```

**Comment by seand7565** [comment]
Hey @stem - yeah, you're right, we need a release! Actually, I think this extension should be ported over to solidus-contrib before doing that. I will get this done soon, thanks!
